#!/bin/bash

source google/env.inc

SRC_DIR=$(readlink -f ${SRC_DIR})
BUILD_DIR=$(readlink -f ./build)
ROOT_DIR=$(readlink -f ./root)

pushd $BUILD_DIR
make clean
popd

[[ "${BUILD_DIR}" != "${SRC_DIR}" ]] && rm -rfv ${BUILD_DIR}
[[ "${ROOT_DIR}" != "${SRC_DIR}" ]] && rm -rfv ${ROOT_DIR}
rm -rfv build root
